FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    systemd systemd-sysv udev dbus \
    iproute2 net-tools curl \
    openssh-server nano passwd kmod netplan.io docker.io python3

RUN echo 'root:root' | chpasswd
RUN echo 'fc-vm' >/etc/hostname

RUN systemctl enable serial-getty@ttyS0.service
RUN systemctl enable systemd-networkd
RUN systemctl enable docker

# Override poweroff to reboot (Firecracker has no ACPI, reboot=k makes reboot exit the VM)
RUN mkdir -p /etc/systemd/system/systemd-poweroff.service.d && printf '[Service]\nExecStart=\nExecStart=/bin/systemctl --force reboot\n' >/etc/systemd/system/systemd-poweroff.service.d/override.conf

COPY 01-netcfg.yaml /etc/netplan/01-netcfg.yaml

RUN apt-get clean && rm -rf /var/lib/apt/lists/*
